### ISSUE TITLE
Generating regular typescript interfaces representing services in ts-proto

### ISSUE THREAD

**Issue by SoftMemes** [deeplay-io/nice-grpc#115]
I have raised this as an issue / feature request on ts-proto as the actual change would be needed there, but would be interested to get the feedback from this end on the proposal, see https://github.com/stephenh/ts-proto/issues/545

In short, I do quite like the model of using a single definition for a service that can be used for service implementations as well as clients, though the Typescript magic required for this on the service side does mean that IDE tooling and error messages are not quite as helpful as they could be.

If ts-proto could generate an actual regular typescript interface that a service would implement, with regular method signatures, then IDE tooling such as "implement interface" would presumably give more readable signatures, and type errors may be somewhat more obvious than what they are now.

Is there anything in principle that would prevent this from working, or being a good idea?

**Comment by aikoven** [comment]
I agree that it would be really nice to have.

One concern is — if we decide to make a breaking change in `nice-grpc` service implementation signatures (or client signatures) — we would have to make a breaking change in `ts-proto` as well, or at least have different plugin options for `nice-grpc` v1 and v2. On the other hand, I don't think that it would happen soon (or at all). Apart from the signatures, the [`ServiceImplementation`](https://github.com/deeplay-io/nice-grpc/blob/nice-grpc%401.1.0/packages/nice-grpc/src/server/ServiceImplementation.ts) and [`Client`](https://github.com/deeplay-io/nice-grpc/blob/nice-grpc%401.1.0/packages/nice-grpc/src/client/Client.ts) types only use types imported from `nice-grpc-common`, which is designed to be very stable. So even if breaking changes in `nice-grpc` affect other parts of it — the generated interfaces should continue to work.

Another concern is the `fromPartial` method. Right now, `nice-grpc` automatically wraps responses on the server and requests on the client with `fromPartial`. So the typings expect service implementation methods to return the `DeepPartial<Response>`. This is not a problem on its own, but we had related problems in the past, for example https://github.com/stephenh/ts-proto/issues/454. I would also like to be able to use shallow partial instead of deep partial in the future, see https://github.com/stephenh/ts-proto/issues/378.

So there are no blockers to your proposal, but there are some things to keep in mind.

**Comment by aikoven** [comment]
Opened a PR: https://github.com/stephenh/ts-proto/pull/555

**Comment by aikoven** [comment]
Starting from version `1.112.0` [`ts-proto`](https://github.com/stephenh/ts-proto) is able to generate TypeScript interfaces for `nice-grpc` service implementations and clients. So instead of `ServiceImplementation<typeof YourServiceDefinition>` you can write `YourServiceImplementation` and instead of `Client<typeof YourServiceDefinition>` just use `YourServiceClient`. This will also make IDE hints more developer-friendly.

To start using this feature, add `outputServices=nice-grpc` to `ts_proto_opt`. Note that `outputServices=nice-grpc` is still required, i.e. you should include `outputServices` option twice. For complete examples see the docs on compiling Protobuf files for [`nice-grpc`](https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc/README.md#using-ts-proto) and [`nice-grpc-web`](https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc-web/README.md#using-ts-proto).

**Comment by SoftMemes** [comment]
This is a great quality of life improvement, much appreciated, and many thanks for taking the feedback onboard so quickly!
