### ISSUE TITLE
Channel creation with custom protocols

### ISSUE THREAD

**Issue by willsoto** [deeplay-io/nice-grpc#167]
Hello! 

I've run into some issues when creating channels with a custom protocol (i.e., not `http` or `https`). This is supported by grpc via [`registerResolver`](https://github.com/grpc/grpc-node/blob/master/packages/grpc-js/src/resolver.ts#L108-L120).

Basically the issue boils down to the channel creation logic here: 

https://github.com/deeplay-io/nice-grpc/blob/22d3f9e050a8804787a4c0959a773eb5dc99bd48/packages/nice-grpc/src/client/channel.ts#L8-L33

I have some thoughts on this logic generally, but in terms of fully supporting grpc, `http` and `https` are not the only protocols one can use (e.g., `consul:`)

I am happy to submit a PR but would like your opinion on what the best approach might be. Here are my initial thoughts:

1. New flag / param indicating that none of the validation should occur and the information should be passed straight through as-is into `new Channel()`. Pro: explicit. Con: additional flag / configuration
2. If `credentials` are provided, the user is opted out of any "validation" by the library. Pro: No new config. Con: implicit and the relationship between credentials and protocol is unclear.
3. Remove validation altogether and allow the grpc-js library to validate. Pro: Less logic in this library, less change for drift in behavior. Con: likely a breaking change because you set credentials conditionally based on protocol. 
4. If parsed protocol is different than `http` or `https`, do not throw an error and instead pass the address *as-is* directly into `new Channel()`. Pro: backwards compatible, no new config. Con: none that I can think of. You will need to set credentials to a default value if not provided, but I think that is not a big deal.

_I currently like option (4) the most since it's (mostly) backwards compatible and allows for custom protocols without any additional configuration._ 

If you have other thoughts, please let me know. 😄 I'm happy to make a PR for any suggestion since I am currently blocked on this issue.

Thank you!

**Comment by aikoven** [comment]
Hey,

First of all, thank you for such a nicely composed proposal!

Option 4 seem like the best to me as well.

> you set credentials conditionally based on protocol

This was the main motivation for making a wrapper around `new Channel()`. We wanted to be able to change endpoints solely by configuration, without touching the code, regardless of secure / insecure, just like you do with plain HTTP. Also to be able to have endpoints of the same format as in `nice-grpc-web`.

Otherwise, option 3 would be preferable to keep things simple. But I think it's fine to have special behavior for `http` and `https`.

Looking forward to see your PR!
