### ISSUE TITLE
[nice-grpc-web] Silent crash on invalid response content

### ISSUE THREAD

**Issue by roboslone** [deeplay-io/nice-grpc#246]
When debugging [uint64 issue](https://github.com/deeplay-io/nice-grpc/issues/245) I had no idea what the problem was until I switched to `WebsocketTransport`. Apparently when `CrossBrowserTransport` can't handle response parsing, it just quits with "response closed without headers" with no errors in console. `WebsocketTransport` on the other hand gave me an actual error which led to related issue.

**Comment by aikoven** [comment]
These transports are implemented in [@improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web), so you're better off filing an issue there.

That said, I'm not sure if it's well supported, so we might want to ship our own patched versions of transports.

**Comment by roboslone** [comment]
[@improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web) doesn't look maintained anymore. Patched transports sound really nice.

**Comment by aikoven** [comment]
Just a quick update:

Decided to go all the way and remove `@improbable-eng/grpc-web` dependency altogether, rewriting `nice-grpc-web` from the ground up. The rewrite itself was easy enough, but making a cross-browser test suite appeared to be really challenging. Also uncovered some incompatibilities that we didn't know about, because we only had tests running on NodeJS, relying on improbable's browser test suite. Will update the docs with compatibility table once finished.
