### ISSUE TITLE
nice-grpc-error-details unstable?

### ISSUE THREAD

**Issue by gogoladzeluk** [deeplay-io/nice-grpc#557]
Hey there! 👋 In the `nice-grpc-error-details` package readme it says:

> This package is experimental and its API should not be considered stable.

What known instability issues does it have? Is there any timeline or schedule as to when it can become "stable"? and any way I can support in that?

Thanks for the great library!

**Comment by aikoven** [comment]
Hey @gogoladzeluk!

When we design library APIs our aim is to make them minimal and ergonomic. To achieve this, we must first try them against real-world code.

With `nice-grpc-error-details` we didn't yet have a chance to do it properly because we don't use rich error model in our company. If and when we start to use it, we might come up with a better API for it which would likely come with a breaking change.

The library is otherwise ready to use.
